version: "3"

services: 
  app:
    container_name: docker-node-app
    restart: always
    build: .
    ports: 
      - "8080:5001"
    links: 
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - "27017:27017"
  